name: Build

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        run: mise install

      - name: Build
        shell: pwsh
        run: |
          Push-Location backend
          uv sync
          uv pip install pyinstaller
          Pop-Location
          Push-Location frontend
          bun install
          bun run build
          Pop-Location
          Push-Location backend
          uv run pyinstaller ocr-camera.spec --noconfirm --distpath ../dist
          Pop-Location

      - uses: actions/upload-artifact@v4
        with:
          name: OCR-Camera-Windows
          path: dist/OCR-Camera.exe
