name: Lint

on:
  push:

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        shell: powershell
        run: |
          mise install
          Push-Location frontend
          mise exec -- bun install
          mise exec -- bun lint
          Pop-Location
          Push-Location backend
          mise exec -- uv run ruff check .
          Pop-Location
